name: KubOS Build

on:
  push:
    tags:
    - '*'

jobs:
  action:
    name: Build KubOS image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          ref: 'buildroot-2022-02'

      - name: Download buildroot
        working-directory: ../
        run: |
          wget https://buildroot.org/downloads/buildroot-2022.02.1.tar.gz
          tar xzf buildroot-2022.02.1.tar.gz

      - name: Configure buildroot
        working-directory: ../buildroot-2022.02.1
        run: make BR2_EXTERNAL=../kubos-linux-build/ beaglebone-black_defconfig

      - name: Build buildroot
        working-directory: ../buildroot-2022.02.1
        run: make

      - name: Save images
        working-directory: ../buildroot-2022.02.1
        run: tar czf ../kubos-linux-build/images.tgz ./output/images

      - uses: ncipollo/release-action@v1
        with:
          artifacts: "images.tgz"
          token: ${{ secrets.GITHUB_TOKEN }}
